server.port=8080

spring.datasource.url=${ACP_POSTGRES}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

acp.s3.endpoint=${ACP_S3}
acp.dynamodb.endpoint=${ACP_DYNAMODB}
